server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ENC(mCQWG3wkSbLuNRXWuIUpHaoFWLkb3DHdGXVFwg8h3TPMWS38gw3p8NdJUqSLLeVOxQssvG3je47GuAyZh2wzCarqayBSSGqeBog1CJNqYuJPun+nY4aDUCVyLILEGOmtpk6dA1PbZ9Y6ASI08Wu+DLphm65no4SIjL7MG7PBmis4EIMb3X2S8C6BkERJkXyq)
    username: ENC(XkM9BQjcc07iKvc2avyN7dYrZ7kQyFZR)
    password: ENC(xDrfzOmNQAdLiLzOn0OUPMHlkdSN4FtT)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 직접 ddl 문을 써주는게 좋긴하다.
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false
    # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정 -> 컨트롤러에서 지연로딩으로 연관된 엔티티를 가지고 오려고하면 에러 발생


  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB 제한
      max-request-size: 100MB # 파일 업로드 요청시 모든 파일 크기합을 100MB 제한

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000



kakao:
  client:
    id: ENC(LCbIEwayURg6qQ+WFjk1qw+ZYJNYy+sgSp7Q8A2nwCOyd6rqxACeQwfzKnt9SGnv)
    secret: ENC(kPhA/tVaOHOFdf5WfORzQUMn5GNT20PMb0ALVcTOz/CPNddJPpM0PfLN+0RV1/XK)

token:
  secret: ENC(W9j3yOdJZBudW8SLX/esPX5cIqMYFe4jj2WQ+EV/GwIhUf9cxUh7kQ==) # 임의의 문자열
  access-token-expiration-time: 900000  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)


jasypt:
  password: ${PASSWORD}

